#+OPTIONS: tex:t
#+STARTUP: latexpreview
#+LaTeX_HEADER: \usepackage{amsmath}
#+TITLE: igamma
#+AUTHOR: Written By Eric Kostlan & Dmitry Gokhman; code converted using TO_F90 by Alan Miller; modifications and language bindings by Mac Radigan
#+HOMEPAGE: https://jblevins.org/mirror/amiller/
#+SEE-ALSO: http://zeta.math.utsa.edu/~gokhman/ftp/papers/igf.pdf
#+LICENSE: ODC Public Domain Dedication & License 1.0
#+SPDX-License-Identifier: PDDL-1.0

** definition

[[https://en.wikipedia.org/wiki/Incomplete_gamma_function#Definition][ltxpng/.equations_46aa4fc9e7780dad4f8899f54da19cdd8a48cbba.png]] 

** source

This repository contains sources released into the public domain, and may be found here in Allan Miller's Fortran Software page:

[[https://jblevins.org/mirror/amiller/cincgam.f90]]

** documentation

Documentation for the original implementation attributed to Eric Kostlan and Dmitry Gokhman can be found at:

[[http://zeta.math.utsa.edu/~gokhman/ftp/papers/igf.pdf]]

** modifications

All subsequent modifications and language bindings I have added are placed in the public domain.

** NO WARRANTY

THE PROGRAM IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL, BUT WITHOUT ANY WARRANTY. IT IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW THE AUTHOR WILL BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF THE AUTHOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

 # *EOF* 
